### ISSUE TITLE
Error on dataview Grouping 

### ISSUE THREAD

**Issue by mad786** [ghiscoding/Angular-Slickgrid#237]
## General Question, Topic
Grouping not working in dataview. Blocked issue.

### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 8
| Angular-Slickgrid |
| TypeScript        |
| Operating System  |
| NPM/Node/Yarn     |

### Context

![SlickGrid_error](https://user-images.githubusercontent.com/52826695/61130577-040ebd00-a4c8-11e9-9b91-1ae12321544d.PNG)

Please help asap.

**Comment by ghiscoding** [comment]
Unless you provide more info, I cannot help you. What is the code that you used, at the least the column definitions? 

> Please help asap.

I think you should read the MIT license... 

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

**Comment by mad786** [comment]
I have tried to use the examples as it is for
 https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-grouping.component.ts

and getting this error for function call 'groupByDurationOrderByCount'.

Any idea why so?

Thanks for helping.

**Comment by ghiscoding** [comment]
All of the grouping on this [Example 14](https://ghiscoding.github.io/Angular-Slickgrid/#/grouping) are working without any console errors. Note that I pushed a new release last night, you might want to make sure that you are using the latest. I also suggest you to clone the [Angular-Slickgrid with Bootstrap 4](https://github.com/ghiscoding/angular-slickgrid-bs4-demo) demo, this might help you

**Comment by ghiscoding** [comment]
closing as there was no feedback, neither code sample was provided and the example works just fine as it was mentioned in my previous post. I can re-open if need be

**Comment by mad786** [comment]
Issue still persists. I have tried your example and is working fine. But you have integrated an internal module for that and i have used npm module angular-slickgrid. What i saw after some analysis is the the aggregator is not working. It is always zero. If i remove the aggregator. The grouping is working but without the aggregator. See screenshot below for reference:

![Aggregator_Error](https://user-images.githubusercontent.com/52826695/61433361-211e1280-a944-11e9-8af7-0fc646ca669a.PNG)



Can you please provide some help on that. 
Thanks.

**Comment by ghiscoding** [comment]
I simply cannot help you since you did not provide any code to replicate your problem, which I asked earlier. Like I said, the example works just fine, so it's you to understand how it works and connect the dots.
