### ISSUE TITLE
Issue in multiselect with filter, doesn't show correct selected list if using filter.

### ISSUE THREAD

**Issue by doll612** [ghiscoding/Angular-Slickgrid#249]
## I'm submitting a Bug report
BUG
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 7.1.4
| Angular-Slickgrid |  2.9.8
| TypeScript        | 3.1.6
| Operating System  | win 10
| NPM/Node/Yarn     | 6.4.1/ 10.13.0

### Context

I was trying to select list by filtering the list.

Steps I have followed:
===============

1. I have selected Task 2.
2. I have filtered Task 2, in this scenario task 2 should be selected, but in the filtered list Task 2 is showing unselected, and at Task 21 is showing selected ( Task 21 I haven't selected before).
3. Again selected Task 2 in the filtered list, and removed the filter.
4. Now in the final selected result list, only Task 2 should be selected, but in the final result list, it is showing Task 0 and Task 2 as a selected list.

### Expected Behavior

1. Task 2 must be selected in the filtered list (already selected data rows must be selected while 
   filtering).
2. Task 21 is never selected before the filter or after the filter, so it should not view as selected in the filtered list.
3. Task 0 should not be selected after removing the filter, because it was never selected.

### Current Behavior

1. I have selected Task 2.
2. I have filtered Task 2, in this scenario task 2 should be selected, but in the filtered list Task 2 is showing unselected, and at Task 21 is showing selected ( Task 21 I haven't selected before).
3. Again selected Task 2 in the filtered list, and removed the filter.
4. Now in the final selected result list, only Task 2 should be selected, but in the final result list, it is showing Task 0 and Task 2 as a selected list.

 Please find attached clip:

[slickGrid issue.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/3438465/slickGrid.issue.zip)

**Comment by ghiscoding** [comment]
Hello, I don't open any zip file for security reason. Can you replicate this behavior in any of the demo/examples provided? I don't see this problem in [Row Selection Example](https://ghiscoding.github.io/Angular-Slickgrid/#/selection) and if I cannot replicate the issue, then I can't fix it. We use it in a couple of our projects and we did not observe that kind of problems with row selection.

**Comment by doll612** [comment]
Hi @ghiscoding ,

I have attached word file in which describe the steps followed to replicate the issue with screenshots, could you please review?

Thanks,
[multiselectIssue.docx](https://github.com/ghiscoding/Angular-Slickgrid/files/3438571/multiselectIssue.docx)

**Comment by doll612** [comment]
1.	First time I have selected Task 2.

![slickGridI1](https://user-images.githubusercontent.com/27808434/61999416-ec495280-b0dd-11e9-8383-cae9a219ac6d.png)

2.	I have filtered Task 2, in this scenario task 2 should be selected, but in the filtered list Task 2 is showing unselected, and at Task 21 is showing selected (Task 21 I haven't selected before).

![slickGrid2](https://user-images.githubusercontent.com/27808434/61999434-519d4380-b0de-11e9-9f4a-8e6bd22c973e.png)

3.	Again selected Task 2 in the filtered list, Task 21 never selected.

![slickGrid3](https://user-images.githubusercontent.com/27808434/61999432-44805480-b0de-11e9-82dd-c1d95967f6d6.png)

4.	Now in the final selected result list, only Task 2 should be selected, but in the final result list, it is showing Task 0 and Task 2 as a selected or checked in the list.

![slickGrid4](https://user-images.githubusercontent.com/27808434/61999438-6ed21200-b0de-11e9-92c6-8c16ebf3c73b.png)

**Comment by ghiscoding** [comment]
Oh I see, good catch, thanks for the full explanation, I can now replicate. The problem is that the `FilterService` has no clue about row selections and for that reason, the selection remains on the row position it was prior to the filtering. This is actually the behavior that my code is (was) supposed to do, which is to clear selection on filter change, but this new regression bug got introduced after I refactored all the Extensions code. I'll take a look at that next week. Thanks

**Comment by ghiscoding** [comment]
Fixed and pushed new version `2.9.9`, the demo was also updated and you can see the fix in [Example 10](https://ghiscoding.github.io/Angular-Slickgrid/#/selection), the row selection gets cleared out after filtering

Thanks for reporting the issue. 

![2019-07-29_14-22-22](https://user-images.githubusercontent.com/643976/62072260-4d6f4400-b20c-11e9-8ced-02ec85f36fa6.gif)

**Comment by doll612** [comment]
Hi @ghiscoding , still the issue is not resolved, it is not working. Now it is not showing the selected rows after removing the filter. The selected row must be checked after removing the filter.

Thanks,

**Comment by ghiscoding** [comment]
This is the behavior that I have to keep, you can see this new behavior in the animated gif. I did mention earlier that the `FilterService` has no clue about the row selection (selected row) and because of that, the best and easiest I can do is to clear the row selection. Keeping trace of all the selected rows and re-selecting them after the filtering is done, would require a lot of extra logic (dealing with async stuff and everything else) and for that reason I will keep the clear selection.
